# main text of home
title: "Emma Abraham"
author: "Emma Abraham"
description: "Clemson University Student"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

picture: ./Best.jpg

url: https://emmaabraham04.github.io/
# your url: http://USERNAME.github.io

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
