# main text of home
title: "Emma Abraham"
author: "Emma Abraham"
description: "Clemson University Student"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

<div style="text-align: center;">
  <img src="./Best.jpg" alt="Profile Picture" width="200" height="200" style="border-radius: 50%;">
</div>
# picture: ./Best.jpg

url: https://emmaabraham04.github.io/
# your url: http://USERNAME.github.io

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
